export interface Surah {
  number: number;
  nameFr: string;
  nameAr: string;
  ayahs: number;
}

/**
 * Les 114 sourates du Coran avec le décompte de versets du mushaf Hafs/Kufi.
 * Total des versets : 6236 (vérifié par le script de génération).
 */
export const SURAHS: readonly Surah[] = [
  { number: 1, nameFr: 'Al-Fātiha', nameAr: 'الفاتحة', ayahs: 7 },
  { number: 2, nameFr: 'Al-Baqara', nameAr: 'البقرة', ayahs: 286 },
  { number: 3, nameFr: 'Āl-ʿImrān', nameAr: 'آل عمران', ayahs: 200 },
  { number: 4, nameFr: 'An-Nisāʾ', nameAr: 'النساء', ayahs: 176 },
  { number: 5, nameFr: 'Al-Māʾida', nameAr: 'المائدة', ayahs: 120 },
  { number: 6, nameFr: 'Al-Anʿām', nameAr: 'الأنعام', ayahs: 165 },
  { number: 7, nameFr: 'Al-Aʿrāf', nameAr: 'الأعراف', ayahs: 206 },
  { number: 8, nameFr: 'Al-Anfāl', nameAr: 'الأنفال', ayahs: 75 },
  { number: 9, nameFr: 'At-Tawba', nameAr: 'التوبة', ayahs: 129 },
  { number: 10, nameFr: 'Yūnus', nameAr: 'يونس', ayahs: 109 },
  { number: 11, nameFr: 'Hūd', nameAr: 'هود', ayahs: 123 },
  { number: 12, nameFr: 'Yūsuf', nameAr: 'يوسف', ayahs: 111 },
  { number: 13, nameFr: 'Ar-Raʿd', nameAr: 'الرعد', ayahs: 43 },
  { number: 14, nameFr: 'Ibrāhīm', nameAr: 'إبراهيم', ayahs: 52 },
  { number: 15, nameFr: 'Al-Hijr', nameAr: 'الحجر', ayahs: 99 },
  { number: 16, nameFr: 'An-Nahl', nameAr: 'النحل', ayahs: 128 },
  { number: 17, nameFr: 'Al-Isrāʾ', nameAr: 'الإسراء', ayahs: 111 },
  { number: 18, nameFr: 'Al-Kahf', nameAr: 'الكهف', ayahs: 110 },
  { number: 19, nameFr: 'Maryam', nameAr: 'مريم', ayahs: 98 },
  { number: 20, nameFr: 'Tā-Hā', nameAr: 'طه', ayahs: 135 },
  { number: 21, nameFr: 'Al-Anbiyāʾ', nameAr: 'الأنبياء', ayahs: 112 },
  { number: 22, nameFr: 'Al-Hajj', nameAr: 'الحج', ayahs: 78 },
  { number: 23, nameFr: 'Al-Muʾminūn', nameAr: 'المؤمنون', ayahs: 118 },
  { number: 24, nameFr: 'An-Nūr', nameAr: 'النور', ayahs: 64 },
  { number: 25, nameFr: 'Al-Furqān', nameAr: 'الفرقان', ayahs: 77 },
  { number: 26, nameFr: 'Ash-Shuʿarāʾ', nameAr: 'الشعراء', ayahs: 227 },
  { number: 27, nameFr: 'An-Naml', nameAr: 'النمل', ayahs: 93 },
  { number: 28, nameFr: 'Al-Qasas', nameAr: 'القصص', ayahs: 88 },
  { number: 29, nameFr: 'Al-ʿAnkabūt', nameAr: 'العنكبوت', ayahs: 69 },
  { number: 30, nameFr: 'Ar-Rūm', nameAr: 'الروم', ayahs: 60 },
  { number: 31, nameFr: 'Luqmān', nameAr: 'لقمان', ayahs: 34 },
  { number: 32, nameFr: 'As-Sajda', nameAr: 'السجدة', ayahs: 30 },
  { number: 33, nameFr: 'Al-Ahzāb', nameAr: 'الأحزاب', ayahs: 73 },
  { number: 34, nameFr: 'Sabaʾ', nameAr: 'سبأ', ayahs: 54 },
  { number: 35, nameFr: 'Fātir', nameAr: 'فاطر', ayahs: 45 },
  { number: 36, nameFr: 'Yā-Sīn', nameAr: 'يس', ayahs: 83 },
  { number: 37, nameFr: 'As-Sāffāt', nameAr: 'الصافات', ayahs: 182 },
  { number: 38, nameFr: 'Sād', nameAr: 'ص', ayahs: 88 },
  { number: 39, nameFr: 'Az-Zumar', nameAr: 'الزمر', ayahs: 75 },
  { number: 40, nameFr: 'Ghāfir', nameAr: 'غافر', ayahs: 85 },
  { number: 41, nameFr: 'Fussilat', nameAr: 'فصلت', ayahs: 54 },
  { number: 42, nameFr: 'Ash-Shūrā', nameAr: 'الشورى', ayahs: 53 },
  { number: 43, nameFr: 'Az-Zukhruf', nameAr: 'الزخرف', ayahs: 89 },
  { number: 44, nameFr: 'Ad-Dukhān', nameAr: 'الدخان', ayahs: 59 },
  { number: 45, nameFr: 'Al-Jāthiya', nameAr: 'الجاثية', ayahs: 37 },
  { number: 46, nameFr: 'Al-Ahqāf', nameAr: 'الأحقاف', ayahs: 35 },
  { number: 47, nameFr: 'Muhammad', nameAr: 'محمد', ayahs: 38 },
  { number: 48, nameFr: 'Al-Fath', nameAr: 'الفتح', ayahs: 29 },
  { number: 49, nameFr: 'Al-Hujurāt', nameAr: 'الحجرات', ayahs: 18 },
  { number: 50, nameFr: 'Qāf', nameAr: 'ق', ayahs: 45 },
  { number: 51, nameFr: 'Adh-Dhāriyāt', nameAr: 'الذاريات', ayahs: 60 },
  { number: 52, nameFr: 'At-Tūr', nameAr: 'الطور', ayahs: 49 },
  { number: 53, nameFr: 'An-Najm', nameAr: 'النجم', ayahs: 62 },
  { number: 54, nameFr: 'Al-Qamar', nameAr: 'القمر', ayahs: 55 },
  { number: 55, nameFr: 'Ar-Rahmān', nameAr: 'الرحمن', ayahs: 78 },
  { number: 56, nameFr: 'Al-Wāqiʿa', nameAr: 'الواقعة', ayahs: 96 },
  { number: 57, nameFr: 'Al-Hadīd', nameAr: 'الحديد', ayahs: 29 },
  { number: 58, nameFr: 'Al-Mujādila', nameAr: 'المجادلة', ayahs: 22 },
  { number: 59, nameFr: 'Al-Hashr', nameAr: 'الحشر', ayahs: 24 },
  { number: 60, nameFr: 'Al-Mumtahana', nameAr: 'الممتحنة', ayahs: 13 },
  { number: 61, nameFr: 'As-Saff', nameAr: 'الصف', ayahs: 14 },
  { number: 62, nameFr: 'Al-Jumuʿa', nameAr: 'الجمعة', ayahs: 11 },
  { number: 63, nameFr: 'Al-Munāfiqūn', nameAr: 'المنافقون', ayahs: 11 },
  { number: 64, nameFr: 'At-Taghābun', nameAr: 'التغابن', ayahs: 18 },
  { number: 65, nameFr: 'At-Talāq', nameAr: 'الطلاق', ayahs: 12 },
  { number: 66, nameFr: 'At-Tahrīm', nameAr: 'التحريم', ayahs: 12 },
  { number: 67, nameFr: 'Al-Mulk', nameAr: 'الملك', ayahs: 30 },
  { number: 68, nameFr: 'Al-Qalam', nameAr: 'القلم', ayahs: 52 },
  { number: 69, nameFr: 'Al-Hāqqa', nameAr: 'الحاقة', ayahs: 52 },
  { number: 70, nameFr: 'Al-Maʿārij', nameAr: 'المعارج', ayahs: 44 },
  { number: 71, nameFr: 'Nūh', nameAr: 'نوح', ayahs: 28 },
  { number: 72, nameFr: 'Al-Jinn', nameAr: 'الجن', ayahs: 28 },
  { number: 73, nameFr: 'Al-Muzzammil', nameAr: 'المزمل', ayahs: 20 },
  { number: 74, nameFr: 'Al-Muddaththir', nameAr: 'المدثر', ayahs: 56 },
  { number: 75, nameFr: 'Al-Qiyāma', nameAr: 'القيامة', ayahs: 40 },
  { number: 76, nameFr: 'Al-Insān', nameAr: 'الإنسان', ayahs: 31 },
  { number: 77, nameFr: 'Al-Mursalāt', nameAr: 'المرسلات', ayahs: 50 },
  { number: 78, nameFr: 'An-Nabaʾ', nameAr: 'النبأ', ayahs: 40 },
  { number: 79, nameFr: 'An-Nāziʿāt', nameAr: 'النازعات', ayahs: 46 },
  { number: 80, nameFr: 'ʿAbasa', nameAr: 'عبس', ayahs: 42 },
  { number: 81, nameFr: 'At-Takwīr', nameAr: 'التكوير', ayahs: 29 },
  { number: 82, nameFr: 'Al-Infitār', nameAr: 'الانفطار', ayahs: 19 },
  { number: 83, nameFr: 'Al-Mutaffifīn', nameAr: 'المطففين', ayahs: 36 },
  { number: 84, nameFr: 'Al-Inshiqāq', nameAr: 'الانشقاق', ayahs: 25 },
  { number: 85, nameFr: 'Al-Burūj', nameAr: 'البروج', ayahs: 22 },
  { number: 86, nameFr: 'At-Tāriq', nameAr: 'الطارق', ayahs: 17 },
  { number: 87, nameFr: 'Al-Aʿlā', nameAr: 'الأعلى', ayahs: 19 },
  { number: 88, nameFr: 'Al-Ghāshiya', nameAr: 'الغاشية', ayahs: 26 },
  { number: 89, nameFr: 'Al-Fajr', nameAr: 'الفجر', ayahs: 30 },
  { number: 90, nameFr: 'Al-Balad', nameAr: 'البلد', ayahs: 20 },
  { number: 91, nameFr: 'Ash-Shams', nameAr: 'الشمس', ayahs: 15 },
  { number: 92, nameFr: 'Al-Layl', nameAr: 'الليل', ayahs: 21 },
  { number: 93, nameFr: 'Ad-Duhā', nameAr: 'الضحى', ayahs: 11 },
  { number: 94, nameFr: 'Ash-Sharh', nameAr: 'الشرح', ayahs: 8 },
  { number: 95, nameFr: 'At-Tīn', nameAr: 'التين', ayahs: 8 },
  { number: 96, nameFr: 'Al-ʿAlaq', nameAr: 'العلق', ayahs: 19 },
  { number: 97, nameFr: 'Al-Qadr', nameAr: 'القدر', ayahs: 5 },
  { number: 98, nameFr: 'Al-Bayyina', nameAr: 'البينة', ayahs: 8 },
  { number: 99, nameFr: 'Az-Zalzala', nameAr: 'الزلزلة', ayahs: 8 },
  { number: 100, nameFr: 'Al-ʿĀdiyāt', nameAr: 'العاديات', ayahs: 11 },
  { number: 101, nameFr: 'Al-Qāriʿa', nameAr: 'القارعة', ayahs: 11 },
  { number: 102, nameFr: 'At-Takāthur', nameAr: 'التكاثر', ayahs: 8 },
  { number: 103, nameFr: 'Al-ʿAsr', nameAr: 'العصر', ayahs: 3 },
  { number: 104, nameFr: 'Al-Humaza', nameAr: 'الهمزة', ayahs: 9 },
  { number: 105, nameFr: 'Al-Fīl', nameAr: 'الفيل', ayahs: 5 },
  { number: 106, nameFr: 'Quraysh', nameAr: 'قريش', ayahs: 4 },
  { number: 107, nameFr: 'Al-Māʿūn', nameAr: 'الماعون', ayahs: 7 },
  { number: 108, nameFr: 'Al-Kawthar', nameAr: 'الكوثر', ayahs: 3 },
  { number: 109, nameFr: 'Al-Kāfirūn', nameAr: 'الكافرون', ayahs: 6 },
  { number: 110, nameFr: 'An-Nasr', nameAr: 'النصر', ayahs: 3 },
  { number: 111, nameFr: 'Al-Masad', nameAr: 'المسد', ayahs: 5 },
  { number: 112, nameFr: 'Al-Ikhlās', nameAr: 'الإخلاص', ayahs: 4 },
  { number: 113, nameFr: 'Al-Falaq', nameAr: 'الفلق', ayahs: 5 },
  { number: 114, nameFr: 'An-Nās', nameAr: 'الناس', ayahs: 6 },
] as const;

export const TOTAL_SURAHS = 114;

export function getSurah(number: number): Surah | undefined {
  return SURAHS.find(s => s.number === number);
}
